GRANT CONNECT, TEMP ON DATABASE user1 TO user2;
GRANT ALL ON ALL TABLES IN SCHEMA public TO user2;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO user2;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO user2;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO user2;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO user2;

GRANT CONNECT, TEMP ON DATABASE user1 TO user3;
GRANT ALL ON ALL TABLES IN SCHEMA public TO user3;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO user3;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO user3;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO user3;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO user3;



















