TRUNCATE TABLE sports_hall RESTART IDENTITY CASCADE;

TRUNCATE TABLE hspecialization RESTART IDENTITY CASCADE;

TRUNCATE TABLE hall_specialization RESTART IDENTITY CASCADE;

TRUNCATE TABLE "user" RESTART IDENTITY CASCADE;

TRUNCATE TABLE client RESTART IDENTITY CASCADE;

TRUNCATE TABLE preference_in_sport RESTART IDENTITY CASCADE;

TRUNCATE TABLE client_preference RESTART IDENTITY CASCADE;

TRUNCATE TABLE personal_data RESTART IDENTITY CASCADE;

TRUNCATE TABLE address RESTART IDENTITY CASCADE;

TRUNCATE TABLE trainer RESTART IDENTITY CASCADE;

TRUNCATE TABLE trainer_assistant RESTART IDENTITY CASCADE;

TRUNCATE TABLE tspecialization RESTART IDENTITY CASCADE;

TRUNCATE TABLE trainer_specialization RESTART IDENTITY CASCADE;

TRUNCATE TABLE training RESTART IDENTITY CASCADE;

TRUNCATE TABLE conduction RESTART IDENTITY CASCADE;

TRUNCATE TABLE reservation RESTART IDENTITY CASCADE;

TRUNCATE TABLE payment RESTART IDENTITY CASCADE;
